name: deploy

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
                  registry-url: 'https://registry.npmjs.org'
            - name: install dependencies and build
              run: |
                  cd sample
                  npm install
                  npm run build
            - name: deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./sample/dist
                  publish_branch: gh-pages
